-- ========================================================
-- The Cloud Spa DSR - Supabase Database Schema
-- Production Schema for Daily Sales Report (DSR)
-- ========================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------
-- 1. USERS TABLE (Super Admin & Admin Authentication)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'ADMIN', -- Allowed: 'SUPER_ADMIN', 'ADMIN'
  status TEXT NOT NULL DEFAULT 'ACTIVE', -- Allowed: 'ACTIVE', 'INACTIVE'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------
-- 2. DSR_ENTRIES TABLE (Daily Sales Report Customer Entries)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS dsr_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  mobile_number TEXT NOT NULL,
  visit_date DATE NOT NULL DEFAULT CURRENT_DATE,
  time_in TEXT NOT NULL DEFAULT '10:00',
  therapy_name TEXT NOT NULL,
  staff_name TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  payment_mode TEXT NOT NULL DEFAULT 'Cash', -- Allowed: 'Cash', 'UPI', 'Card', 'Mixed'
  remarks TEXT,
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_by_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for performance on DSR querying
CREATE INDEX IF NOT EXISTS idx_dsr_entries_visit_date ON dsr_entries(visit_date);
CREATE INDEX IF NOT EXISTS idx_dsr_entries_payment_mode ON dsr_entries(payment_mode);
CREATE INDEX IF NOT EXISTS idx_dsr_entries_customer ON dsr_entries(customer_name, mobile_number);

-- --------------------------------------------------------
-- 3. SETTINGS TABLE (Application Settings)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------
-- INITIAL SEED DATA
-- Default Super Admin (Email: admin@thecloudspa.in, Password: admin123password)
-- Default Application Settings
-- --------------------------------------------------------
INSERT INTO users (name, email, password_hash, role, status)
VALUES (
  'Super Admin',
  'admin@thecloudspa.in',
  '$2a$10$X8m1g7bI6vD3S8P9/2G1O.N3L7H.4F5J6K7L8M9N0P1Q2R3S4T5U',
  'SUPER_ADMIN',
  'ACTIVE'
)
ON CONFLICT (email) DO NOTHING;

INSERT INTO settings (key, value)
VALUES
  ('spa_name', 'The Cloud Spa'),
  ('spa_address', '4/526 Vivek Khand, Gomti Nagar, Lucknow, 226010, India'),
  ('spa_phone', '9455671995'),
  ('spa_email', 'info@thecloudspa.in'),
  ('currency', 'INR')
ON CONFLICT (key) DO NOTHING;
